services: 
  etl:
    image: etl
    container_name: etl
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      TABLE_NAME: ${TABLE_NAME}
      FILE_PATH: ${FILE_PATH}

  warehouse: 
    image: mysql:13
    container_name: warehouse
    environment: 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    volumes: 
      - MYSQL-volume:/var/lib/MYSQLql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    ports: 
      - "3306:3306"

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - urandom:/dev/random:ro
    ports:
      - 8080:8080
    restart: always

volumes:
  MYSQL-volume:
  urandom: 

